Feat/influxdb
kintohub/charts pull request #2
Opened 2019-10-18 08:53 UTC by Disturbing

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kintohub/charts/2)

2019-10-18 08:54 UTC, Disturbing commented
image.repository=bitnami/influxdb
image.tag=1.7.8-debian-9-r8
database=my_database
authEnabled=true
adminUser.name=admin
adminUser.pwd=coolpass
user.name
user.pwd
readUser.name
readUser.pwd
writeUser.name
writeUser.pwd
influxdb.replicaCount=1
relay.image.repository=bitnami/influxdb-relay
relay.image.tag=0.20161114.0-scratch-r0
relay.replicaCount=1
persistence.enabled=true
persistence.size=8Gi

2019-10-19 00:26 UTC, bappr commented
Missing resources limit

Put values in values.kinto

2019-10-19 00:27 UTC, bakayolo requested changes

2019-10-19 00:27 UTC, bappr commented on stable/influxdb/templates/NOTES.txt
> +- http://{{ template "influxdb.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.config.http.bind_address }}
Remove `.{{ .Release.Namespace }}`

2019-10-21 10:04 UTC, merged