Feat/minio
kintohub/charts pull request #3
Opened 2019-10-18 08:56 UTC by Disturbing

2019-10-18 08:57 UTC, Disturbing commented
image.tag=RELEASE.2019-08-07T01-59-21Z
persistence.size=10Gi
persistence.enabled=true
s3gateway.enabled=false
s3gateway.replicas=3
s3gateway.serviceEndpoint
azuregateway.enabled=false
azuregateway.replicas=3
gcsgateway.enabled=false
gcsgateway.replicas=3
gcsgateway.gcsKeyJson
gcsgateway.projectId
ossgateway.enabled=false
ossgateway.replicas=3
ossgateway.endpointURL
environment.MINIO_BROWSER=on
environment.MINIO_ACCESS_KEY=coolkey
environment.MINIO_SECRET_KEY=coolsecret
environment.MINIO_CACHE_EXCLUDE
environment.MINIO_CACHE_EXPIRY

2019-10-19 00:24 UTC, bappr commented
Missing resources limit

Values in values.kinto

2019-10-19 00:26 UTC, bakayolo requested changes

2019-10-19 00:26 UTC, bappr commented on stable/minio/templates/NOTES.txt
>  {{ template "minio.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
`{{ .Release.Namespace }}.svc.cluster.local` to be removed

2019-10-21 10:12 UTC, merged