:construction: feat(Nats): Nats chart
kintohub/charts pull request #4
Opened 2019-10-18 08:59 UTC by Disturbing

2019-10-18 09:00 UTC, Disturbing commented
image.tag=2.1.0-debian-9-r0
replicaCount=1
auth.enabled=true
auth.user=nats_user
auth.password=undefined
auth.token=undefined
clusterAuth.enabled=true
clusterAuth.user=nats_cluster
clusterAuth.password=undefined
clusterAuth.token=undefined
maxConnections=100
maxControlLine=512
maxPayload=65536
writeDeadline=2s

2019-10-19 00:23 UTC, bappr commented
Missing resources limit

Add values to values.kinto

2019-10-19 00:24 UTC, bakayolo requested changes

2019-10-19 00:24 UTC, bappr commented on stable/nats/templates/NOTES.txt
>     {{ template "nats.fullname" . }}-client.{{ .Release.Namespace }}.svc.cluster.local
Remove `.{{ .Release.Namespace }}.svc.cluster.local`

2019-10-19 00:24 UTC, bappr commented on stable/nats/templates/NOTES.txt
> +    {{ template "nats.fullname" . }}-monitoring.{{ .Release.Namespace }}.svc.cluster.local
`.{{ .Release.Namespace }}.svc.cluster.local` to be removed

2019-10-21 10:14 UTC, merged