Feat/rabbitmq ha
kintohub/charts pull request #5
Opened 2019-10-18 09:05 UTC by Disturbing

2019-10-18 09:07 UTC, Disturbing commented
image.repository=rabbitmq
image.tag=3.7.19-alpine
definitions.users={"name":"myUsername", "password":"myPassword", "tags": "administrator"}
rabbitmqMemoryHighWatermark=256MB
rabbitmqMemoryHighWatermarkType=absolute
replicaCount=3
persistentVolume.enabled=false
persistentVolume.size=8Gi

2019-10-19 00:21 UTC, bappr commented
Missing resources limit

Put values in `values.kinto` for reference

2019-10-19 00:22 UTC, bakayolo requested changes

2019-10-19 00:22 UTC, bappr commented on stable/rabbitmq-ha/templates/NOTES.txt
>    RabbitMQ can be accessed within the cluster on port {{ .Values.rabbitmqNodePort }} at {{ template "rabbitmq-ha.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
Remove `.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}`

2019-10-21 10:10 UTC, merged