feat/redis
kintohub/charts pull request #7
Opened 2019-10-18 09:13 UTC by Disturbing

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kintohub/charts/7)

2019-10-18 09:14 UTC, Disturbing commented
image.repository=redis
image.tag=5.0.5-alpine
replicas=3
auth=false
redisPassword
persistentVolume.enabled=false
persistentVolume.size=10Gi

2019-10-19 00:10 UTC, bappr commented
For every helm chart, suggest we add the kintohub variables
```
image.repository=redis
image.tag=5.0.5-alpine
replicas=3
auth=false
redisPassword
persistentVolume.enabled=false
persistentVolume.size=10Gi
```

in a file `values.kinto` so that anyone can see it and modify them if needed

2019-10-19 00:13 UTC, bakayolo requested changes

2019-10-19 00:13 UTC, bappr commented on stable/redis-ha/templates/NOTES.txt
> +{{ template "redis-ha.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
Remove `.{{ .Release.Namespace }}.svc.cluster.local`
No need and it's too much information.

2019-10-19 00:13 UTC, bappr commented on stable/redis-ha/templates/redis-ha-statefulset.yaml
> -{{ toYaml .Values.securityContext | indent 8 }}
Leaving it empty should have done the job but ok

2019-10-19 00:20 UTC, bappr commented
Missing resources limit

2019-10-21 09:34 UTC, merged